### ISSUE TITLE
Ebitengine imports should point to v2

### ISSUE THREAD

**Issue by tinne26** [theonlymoby/magnetib#1]
Hey, this is more a comment than an issue, feel free to close if you don't want to change this.

I saw in the code that you are using these imports:
```Go
import "github.com/hajimehoshi/ebiten"
```
You probably want the latest versions instead:
```Go
import "github.com/hajimehoshi/ebiten/v2"
import "github.com/hajimehoshi/ebiten/v2/audio/wav"
```

For example, the `wav.DecodeWithSampleRate` function is only available on v2.

**Comment by sjpau** [comment]
Hi, thanks for pointing that out. Corrected to point to v2.
